"""
Django settings for university_erp_backend project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9shp_6-6-vh56yd()on^n#t)ixf)bnbsu!ufh$ghqsfnnu2z2a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

SHARED_APPS = [
    'django_tenants',
    'public_tenant',
    'profiles',
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'djoser',
    'corsheaders', 
    

    
]

TENANT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'profiles',

]

INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
AUTH_USER_MODEL = 'profiles.User'
ROOT_URLCONF = 'university_erp_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # Make sure this is set
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'university_erp_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'ERP_DB',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)
SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "profiles.serializers.CustomTokenObtainPairSerializer",
}

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication', # Optional, for browsable API
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', # Default to require authentication
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Djoser settings
DJOSER = {
    'PASSWORD_RESET_CONFIRM_URL': 'auth/password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'auth/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'auth/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': False, # Set to True if you want email activation
    'SEND_PASSWORD_RESET_EMAIL': True,
    'SERIALIZERS': {
        'user_create': 'profiles.serializers.CustomUserCreateSerializer', # Customize user registration
        'user': 'profiles.serializers.CustomUserSerializer',
        'current_user': 'profiles.serializers.CustomUserSerializer',
    },
    'EMAIL': {
        'password_reset': 'djoser.email.PasswordResetEmail',
        # 'activation': 'djoser.email.ActivationEmail', # Uncomment if SEND_ACTIVATION_EMAIL is True
    },
    'TEMPLATES': {
        'email': {
            'password_reset': 'email/password_reset.html',
        }
    }
}

# Add this setting for the frontend domain
FRONTEND_URL = "http://ypu.localhost:8080"

# For development, allow all origins. In production, specify your React app's domain.
#CORS_ALLOW_ALL_ORIGINS = True
# Or, for specific origins:
CORS_ALLOWED_ORIGINS = [
   "http://localhost:8080", # Your React app's development server
   "http://ypu.localhost:8080",
]

# ... rest of the settings ...

# Email settings for password reset (example with console backend for testing)
# ... existing code ...
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# Looking to send emails in production? Check out our Email API/SMTP product!
EMAIL_HOST = 'sandbox.smtp.mailtrap.io'
EMAIL_HOST_USER = '215d139b9f5664'
EMAIL_HOST_PASSWORD = '15fa07abaefd71'
EMAIL_PORT = '2525'
#
# ... existing code ...
# For production, configure a real email backend like SendGrid, Mailgun, etc.
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = os.environ.get('SENDGRID_API_KEY') # Store securely!

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# If you want to use a custom static directory (for development)
import os
STATICFILES_DIRS = [BASE_DIR / "static"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TENANT_MODEL = "public_tenant.Client"

TENANT_DOMAIN_MODEL = "public_tenant.Domain"


JAZZMIN_SETTINGS = {
    "site_title": "YPU Admin",
    "site_header": "YPU Administration",
    "site_brand": "YPU",
    "welcome_sign": "Welcome to YPU Admin Panel",
    "site_logo": "university-logo.png",
    "site_logo_classes": "img-circle",
    "copyright": "YPU University",
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["profiles", "auth","public_tenant"],
    "icons": {
    "auth": "fas fa-users-cog",
    "profiles.user": "fas fa-user",
    "profiles.studyplan": "fas fa-book",
    "profiles.meeting": "fas fa-calendar-alt",
    # ...etc
},
    # Hide or show apps/models
    "hide_apps": ['public_tenant'],
    "hide_models": ["auth.Group"],
    # Add more settings as needed...
}