# Generated by Django 5.2.4 on 2025-07-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dean', 'Dean'), ('coordinator', 'Coordinator'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
