# Generated by Django 5.2.4 on 2025-07-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyplan',
            old_name='student',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dean', 'Dean'), ('coordinator', 'Coordinator'), ('teacher', 'Teacher')], default='coordinator', max_length=20),
        ),
    ]
