# Generated by Django 5.2.4 on 2025-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_student_studyplan_teacher_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('dean', 'Dean'), ('coordinator', 'Coordinator'), ('teacher', 'Teacher'), ('student', 'Student')], default='coordinator', max_length=20),
        ),
    ]
