# Generated by Django 5.2.4 on 2025-07-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdecision',
            name='gpa',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
