# Generated by Django 5.2.4 on 2025-07-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_academicdecision_gpa_meeting_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
