# Generated by Django 5.2.4 on 2025-07-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
