# Generated by Django 5.2.4 on 2025-07-17 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_user_gpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gpa',
        ),
    ]
